---
####ACTUAL FACT####
  

  - name: "Ensure custom fact directory exists"
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
    with_items:
      - /etc/ansible
      - /etc/ansible/facts.d
      
  - name: Transfering rootaccacckeyexists1_4actual actualfact file
    template:
      src: ../templates/actual_fact/rootaccacckeyexists1_4actual.fact   
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - rootaccacckeyexists1_4actual
      - '1.4'
      - one
      - all

  - name: Transfering mfaenabroot1_5actual actualfact file
    template:
      src: ../templates/actual_fact/mfaenabroot1_5actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - mfaenabroot1_5actual
      - '1.5'
      - one
      - all

  - name: Transfering rootusradmin1_7actual actualfact file
    template:
      src: ../templates/actual_fact/rootusradmin1_7actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - rootusradmin1_7actual
      - '1.7'
      - one
      - all

  - name: Transfering minlength1_8ctual actualfact file
    template:
      src: ../templates/actual_fact/minlength1_8actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - minlength1_8actual
      - '1.8'
      - one
      - all

  - name: Transfering passreuse1_9actual actualfact file
    template:
      src: ../templates/actual_fact/passreuse1_9actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - passreuse1_9actual
      - '1.9'
      - one
      - all

  - name: Transfering mfaenabusers1_10actual actualfact file
    template:
      src: ../templates/actual_fact/mfaenabusers1_10actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - mfaenabusers1_10actual
      - '1.10'
      - one
      - all

  - name: Transfering iamconsolepasswd1_11actual actualfact file
    template:
      src: ../templates/actual_fact/iamconsolepasswd1_11actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - iamconsolepasswd1_11actual
      - '1.11'
      - one
      - all

  - name: Transfering acckeyavailsinguser1_13actual actualfact file
    template:
      src: ../templates/actual_fact/acckeyavailsinguser1_13actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - acckeyavailsinguser1_13actual
      - '1.13'
      - one
      - all

  - name: Transfering acckeyrotninetydays1_14actual actualfact file
    template:
      src: ../templates/actual_fact/acckeyrotninetydays1_14actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - acckeyrotninetydays1_14actual
      - '1.14'
      - one
      - all

  - name: Transfering IAMUsersPermissionGroups1_15actual actualfact file
    template:
      src: ../templates/actual_fact/IAMUsersPermissionGroups1_15actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - IAMUsersPermissionGroups1_15actual
      - '1.15'
      - one
      - all
      
  - name: Transfering fulladminpriv1_16actual actualfact file
    template:
      src: ../templates/actual_fact/fulladminpriv1_16actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - fulladminpriv1_16actual
      - '1.16'
      - one
      - all

  - name: Transfering awssupportaccess1_17actual actualfact file
    template:
      src: ../templates/actual_fact/awssupportaccess1_17actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - awssupportaccess1_17actual
      - '1.17'
      - one
      - all

  - name: Transfering Iaminstrolesawsres_1_18actual actualfact file
    template:
      src: ../templates/actual_fact/Iaminstrolesawsres_1_18actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - Iaminstrolesawsres_1_18actual
      - '1.18'
      - one
      - all

  - name: Transfering s3blockpubaccess1_20actual actualfact file
    template:
      src: ../templates/actual_fact/s3blockpubaccess1_20actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - s3blockpubaccess1_20actual
      - '1.20'
      - one
      - all
      
  - name: Transfering accessanalyzer_1_21_actual actualfact file
    template:
      src: ../templates/actual_fact/accessanalyzer_1_21_actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - accessanalyzer_1_21_actual
      - '1.21'
      - one
      - all

  - name: Transfering s3encryp_2_1_1actual actualfact file
    template:
      src: ../templates/actual_fact/s3encryp_2_1_1actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - s3encryp_2_1_1actual
      - '2.1.1'
      - two
      - all

  - name: Transfering s3http_2_1_2actual actualfact file
    template:
      src: ../templates/actual_fact/s3http_2_1_2actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - s3http_2_1_2actual
      - '2.1.2'
      - two
      - all

  - name: Transfering ebsencryp_2_2_1actual actualfact file
    template:
      src: ../templates/actual_fact/ebsencryp_2_2_1actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ebsencryp_2_2_1actual
      - '2.2.1'
      - two
      - all

  - name: Transfering ctenballreg3_1actual actualfact file
    template:
      src: ../templates/actual_fact/ctenballreg3_1actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ctenballreg3_1actual
      - '3.1'
      - three
      - all

  - name: Transfering ctlogfvalid3_2actual actualfact file
    template:
      src: ../templates/actual_fact/ctlogfvalid3_2actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ctlogfvalid3_2actual
      - '3.2'
      - three
      - all

  - name: Transfering ctnotpubaccess3_3actual actualfact file
    template:
      src: ../templates/actual_fact/ctnotpubaccess3_3actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ctnotpubaccess3_3actual
      - '3.3'
      - three
      - all

  - name: Transfering ctintegcwlogs3_4actual actualfact file
    template:
      src: ../templates/actual_fact/ctintegcwlogs3_4actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ctintegcwlogs3_4actual
      - '3.4'
      - three
      - all

  - name: Transfering awsconfig_3_5actual actualfact file
    template:
      src: ../templates/actual_fact/awsconfig_3_5actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - awsconfig_3_5actual
      - '3.5'
      - three
      - all
    
  - name: Transfering servicelogging3_6actual actualfact file
    template:
      src: ../templates/actual_fact/servicelogging3_6actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - servicelogging3_6actual
      - '3.6'
      - three
      - all

  - name: Transfering ctlogencryp3_7actual actualfact file
    template:
      src: ../templates/actual_fact/ctlogencryp3_7actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ctlogencryp3_7actual
      - '3.7'
      - three
      - all

  - name: Transfering cmkenable3_8actual actualfact file
    template:
      src: ../templates/actual_fact/cmkenable3_8actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - cmkenable3_8actual
      - '3.8'
      - three
      - all

  - name: Transfering flowlog_3_9_actual actualfact file
    template:
      src: ../templates/actual_fact/flowlog_3_9_actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - flowlog_3_9_actual
      - '3.9'
      - three
      - all

  - name: Transfering objlogwrite3_10actual actualfact file
    template:
      src: ../templates/actual_fact/objlogwrite3_10actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - objlogwrite3_10actual
      - '3.10'
      - three
      - all

  - name: Transfering objlogread3_11actual actualfact file
    template:
      src: ../templates/actual_fact/objlogread3_11actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - objlogread3_11actual
      - '3.11'
      - three
      - all

  - name: Transfering lodgmetralaforunauthcalls4_1actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforunauthcalls4_1actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforunauthcalls4_1actual
      - '4.1'
      - four
      - all

  - name: Transfering lodgmetralaformangconsigninmfa4_2actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaformangconsigninmfa4_2actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaformangconsigninmfa4_2actual
      - '4.2'
      - four
      - all
    
  - name: Transfering lodgmetralaforusageofrootacc4_3actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforusageofrootacc4_3actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforusageofrootacc4_3actual
      - '4.3'
      - four
      - all

  - name: Transfering lodgmetralaforIAMpolchanges4_4actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforIAMpolchanges4_4actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforIAMpolchanges4_4actual
      - '4.4'
      - four
      - all

  - name: Transfering lodgmetralaforCTconfigchanges_4_5actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforCTconfigchanges_4_5actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforCTconfigchanges_4_5actual
      - '4.5'
      - four
      - all

  - name: Transfering lodgmetralaforawsmangconsauthfail_4_6actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforawsmangconsauthfail_4_6actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforawsmangconsauthfail_4_6actual
      - '4.6'
      - four
      - all

  - name: Transfering lodgmetralafordelofCMK_4_7actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralafordelofCMK_4_7actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralafordelofCMK_4_7actual
      - '4.7'
      - four
      - all

  - name: Transfering lodgmetralafors3buckpolchanges4_8actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralafors3buckpolchanges4_8actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralafors3buckpolchanges4_8actual
      - '4.8'
      - four
      - all

  - name: Transfering lodgmetralaforawsconfigchanges_4_9actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforawsconfigchanges_4_9actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforawsconfigchanges_4_9actual
      - '4.9'
      - four
      - all

  - name: Transfering lodgmetralaforsecgrpchanges4_10actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforsecgrpchanges4_10actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforsecgrpchanges4_10actual
      - '4.10'
      - four
      - all

  - name: Transfering lodgmetralaforNACL4_11actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforNACL4_11actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforNACL4_11actual
      - '4.11'
      - four
      - all

  - name: Transfering lodgmetralafornetworkgatway4_12actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralafornetworkgatway4_12actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - ipforwarding
      - '4.12'
      - four
      - all

  - name: Transfering lodgmetralaforrouttabchang4_13actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforrouttabchang4_13actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforrouttabchang4_13actual
      - '4.13'
      - four
      - all

  - name: Transfering lodgmetralaforvpcchang4_14actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforvpcchang4_14actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforvpcchang4_14actual
      - '4.14'
      - four
      - all

  - name: Transfering lodgmetralaforawsorgchang4_15actual actualfact file
    template:
      src: ../templates/actual_fact/lodgmetralaforawsorgchang4_15actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - lodgmetralaforawsorgchang4_15actual
      - '4.15'
      - four
      - all

  - name: Transfering networkaclingress5_1actual actualfact file
    template:
      src: ../templates/actual_fact/networkaclingress5_1actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - networkaclingress5_1actual
      - '5.1'
      - five
      - all

  - name: Transfering securitygrping5_2actual actualfact file
    template:
      src: ../templates/actual_fact/securitygrping5_2actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - securitygrping5_2actual
      - '5.2'
      - five
      - all

  - name: Transfering securitygrpalltraf5_3actual actualfact file
    template:
      src: ../templates/actual_fact/securitygrpalltraf5_3actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - securitygrpalltraf5_3actual
      - '5.3'
      - five
      - all

  - name: Transfering vpcleastaccess5_4actual actualfact file
    template:
      src: ../templates/actual_fact/vpcleastaccess5_4actual.fact
      dest: /etc/ansible/facts.d/
      mode: 0755
    tags:
      - vpcleastaccess5_4actual
      - '5.4'
      - five
      - all 

  - name: reload ansible_local
    setup: filter=ansible_local
    tags:
      - always 
